#*****************************************************************
# Generated by Board2Make (https://github.com/luni64/Board2Make)
#
# Board              Teensy LC
# USB Type           Serial
# CPU Speed          48 MHz
# Optimize           Smallest Code
# Keyboard Layout    US English
#
# 29.08.2018 11:00
#*****************************************************************

BOARD_ID   := TEENSYLC

FLAGS_CPU  := -mthumb -mcpu=cortex-m0plus -fsingle-precision-constant
FLAGS_OPT  := -Os --specs=nano.specs
FLAGS_COM  := -g -Wall -ffunction-sections -fdata-sections -nostdlib -MMD
FLAGS_LSP  := 

FLAGS_CPP  := -fno-exceptions -felide-constructors -std=gnu++14 -Wno-error=narrowing -fno-rtti
FLAGS_C    := 
FLAGS_S    := -x assembler-with-cpp
FLAGS_LD   := -Wl,--gc-sections,--relax,--defsym=__rtc_localtime=0

LIBS       := -larm_cortexM0l_math -lm
LD_SCRIPT  := mkl26z64.ld

DEFINES    := -D__MKL26Z64__ -DTEENSYDUINO=142
DEFINES    += -DF_CPU=48000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH

CPP_FLAGS  := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_COM) $(DEFINES) $(FLAGS_CPP)
C_FLAGS    := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_COM) $(DEFINES) $(FLAGS_C)
S_FLAGS    := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_COM) $(DEFINES) $(FLAGS_S)
LD_FLAGS   := $(FLAGS_CPU) $(FLAGS_OPT) $(FLAGS_LSP) $(FLAGS_LD)
AR_FLAGS   := rcs
